//
// Created by Zane Claes on 1/21/26.
//

#ifndef AUTO_PLANT_WATERER_WATER_PUMPS_H
#define AUTO_PLANT_WATERER_WATER_PUMPS_H

#define PUMP1_GPIO  (GPIO_NUM_2)
#define PUMP2_GPIO  (GPIO_NUM_3)
#define PUMP3_GPIO  (GPIO_NUM_4)

#endif //AUTO_PLANT_WATERER_WATER_PUMPS_H